
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Let gunicorn set this environment variable or set a random string here
    secret_key: _env:SECRET_KEY


# This is the default configuration when no flavor is specified
dev:
    storage: local
    storage_path: /data/docker-registry-data
    loglevel: debug

# To specify another flavor, set the environment variable SETTINGS_FLAVOR
# $ export SETTINGS_FLAVOR=prod
prod:
    storage: local 
    storage_path: /data/docker-registry-data
    # Enabling these options makes the Registry send an email on each code Exception
    email_exceptions:
        smtp_host: REPLACEME
        smtp_port: 25
        smtp_login: REPLACEME
        smtp_password: REPLACEME
        smtp_secure: false
        from_addr: docker-registry@localdomain.local
        to_addr: noise+dockerregistry@localdomain.local

# This flavor is automatically used by unit tests
test:
    storage: local
    storage_path: /tmp/test
